[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
extism-pdk = "1.0.0"
moon_pdk = "0.0.1"
moon_pdk_test_utils = "0.0.1"
starbase_sandbox = "0.1.13"

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "s"
panic = "abort"
